version: '3'

services:
  mysql:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: local-mysql
    restart: always
    command: 
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: dev
      MYSQL_ROOT_PASSWORD: 0000
      TZ: Asia/Seoul
    volumes:
      - ./mysql/db:/var/lib/mysql