version: '3.1'

services:
  mysql:
    image: mysql:latest
    container_name: mysql8
    restart: always
    command: 
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: dev
      TZ: Asia/Seoul